### ISSUE TITLE
Is there any audio sample?

### ISSUE THREAD

**Issue by jc5201** [etzinis/heterogeneous_separation#2]
Is there any audio sample?
Unfortunately source code is not available until now...

**Comment by soowhanchung** [comment]
I'm also looking forward to listening to some audio demos.
I'm also curious what will happen if you condition "A concept" on a model while there is no "A concept signal" in a mixture.

**Comment by etzinis** [comment]
Hello there and sory for the delay to respond. The dataset loaders are available right now because of several issues with the IP of MERL, I think training a model with this is pretty straightforward now. 

I will try to make a demo notebook or just upload a few demo samples but the paper mostly cares about the training process. We have several results on the paper showing how our models can cope with degenerate cases (all sources belong or all sources do not belong to the target waveform, please see Section 4.3 in the paper https://www.isca-speech.org/archive/pdfs/interspeech_2022/tzinis22_interspeech.pdf)

**Comment by etzinis** [comment]
As promised here are some audio samples. https://etzinis.github.io/projects_demos/heterogeneous.html 

I also included some degenerate cases as @soowhanchung mentioned where either the target source waveform is zero or the input-mixture! enjoy!
